FROM node:20-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci --production

FROM node:20-alpine

WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY . .

EXPOSE 7000

CMD ["node", "index.js"]
